version: 2.1
jobs:
  Run-Test:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run:
          name: Build Docker Image
          command: |
            docker build -t dockerifont21/react-test -f ./client/Dockerfile.dev ./client
      - run:
          name: Run Tests
          command: |
            docker run -e CI=true dockerifont21/react-test npm run test
workflows:
  Pipeline:
    jobs:
      - Run-Test