version: 2.1
jobs:
  Run-Test:
    machine:
      image: ubuntu-2004:202010-01
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Build Docker Image
          command: docker build -t dockerifont21/react-test -f ./client/Dockerfile.dev ./client
      - run:
          name: Test App
          command: docker run -e CI=true dockerifont21/react-test npm test
  Deploy:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Setting up GCloud
          command: |
            openssl aes-256-cbc -d -md sha256 -in service-account.enc -out service-account.json -pass pass:$CIRCLECI_ENC_VAR_OPENSSL_PASS
            curl https://sdk.cloud.google.com | bash > /dev/null;
            source $HOME/google-cloud-sdk/path.bash.inc
            gcloud components update kubectl
            gcloud auth activate-service-account --key-file service-account.json
            gcloud config set project my-multi-k8
            gcloud config set compute/zone europe-west1-b
            gcloud container clusters get-credentials multi-k8-cluster
workflows:
  Pipeline:
    jobs:
      - Run-Test
      - Deploy:
          requires:
            - Run-Test 