apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ifontcode-dev-tls
spec:
  secretName: ifontcode-dev
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: ifontcode.dev
  dnsNames:
    - ifontcode.dev
    - www.ifontcode.dev